### ISSUE TITLE
Dodělat funkci vytisknutí registrů a stavového slova cpu

### ISSUE THREAD

**Issue by Vrbikk** [cervenkam/os#12]
Něco už jsem commitnul ale nedokážu vyřešit výpis jednotlivých popisů registrů... tipuju si na problém se segmentací Márty halp pls

tuhle funkci potřebujeme nebo jsme nahraný

**Comment by cervenkam** [comment]
Problem je se ctenim z disku..., stejne jako zapis i cteni nefunguje uplne spravne ;/, proto jsem znova otevrel issue "Loader"
Dobre je to videt na nacitacim obrazku... seskupil jsem includy jinak, aby byl obrazek na konci kodu a konec obrazku jsou jenom random pixely => neni to nacteny z disku :/
