### ISSUE TITLE
Správa paměti?

### ISSUE THREAD

**Issue by stechy1** [cervenkam/os#5]
Neměli bychom implementovat i nějakou správu paměti?

**Comment by cervenkam** [comment]
U davkoveho systemu? tam prece nepotrebujes nijak slozitou spravu pameti, takze bych ji asi udelal statickou ;) - proste si reknes, potrebuju pamet od 0xabcd do 0xef01 a budem vedet, ze ji nikdo jiny pouzit nesmi ;)

**Comment by cervenkam** [comment]
U davkoveho systemu? tam prece nepotrebujes nijak slozitou spravu pameti, takze bych ji asi udelal statickou ;) - proste si reknes, potrebuju pamet od 0xabcd do 0xef01 a budem vedet, ze ji nikdo jiny pouzit nesmi ;)

Mrkni na: https://cs.wikipedia.org/wiki/Spr%C3%A1va_pam%C4%9Bti#Historie
