### ISSUE TITLE
Registrace klávesnice na HW přerušení

### ISSUE THREAD

**Issue by Vrbikk** [cervenkam/os#7]
zjistit možnosti jak pomocí klávesnice způsobit nějakou akci

**Comment by cervenkam** [comment]
Musi se rict PICcku, ze uz nechces, aby ho obsluhoval BIOS, ale ze pro nej udelas obsluhu v IDT, no a v IDT pak staci predat informace o stisknute klavese bezicimu programu ;)

V podstate to vyzaduje 2 akce:

1. Preprogramovat PICcko (sdelit mu, kde se nachazi IDT a od ktereho prvku se ma mapovat
2. Vytvorit obsluhu preruseni pro stisk klavesy, ktera preda informace dal

Vycerpavajici popis: http://wiki.osdev.org/Interrupts
