### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by cervenkam** [cervenkam/os#9]
Je potreba navrhnout zpusob, jak se nacte kod do pameti, protoze bootloader nacte jen 512B kodu, zbytek lezi na disku -> nejspis budeme muset udelat nejaky loader z disku do RAM...

**Comment by Vrbikk** [comment]
našel jsem celkem pěknou ukázku bootloaderu zavádějící kernel v C
http://web.uvic.ca/~salam/os/guide.html
dobrý nápad udělat z toho .iso a spouštět to "qemu-system-x86_64 -boot d -cdrom khudi.iso"

**Comment by cervenkam** [comment]
Je to pekna ukazka bootloaderu ;), dost minimalisticky..., ale kdyz si z toho jenom vezmem ISO, tak nebudeme vedet, jak cist z disku, coz budeme potrebovat napr. ve filesystemu...
Videl bych to teda jako dobry navod, jak si bootloader udelat ;)

**Comment by Vrbikk** [comment]
ok tak jen ten bootloader a disk si musíme udělat zvlášť nu...

**Comment by cervenkam** [comment]
Uzaviram issue, uz mame nejakou pamet a neni problem ji rozumne zvetsovat

**Comment by cervenkam** [comment]
Loader nacte mensi cast pameti, nez jsem cekal, proste BIOS a prace s diskem je divna....
